# Generated by Django 5.2.6 on 2025-10-21 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_paymentcourses"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PaymentCourses",
            new_name="PaymentCourse",
        ),
    ]
