# Generated by Django 5.2.6 on 2025-10-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_rename_paymentcourses_paymentcourse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentcourse",
            name="link",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на оплату",
                max_length=1000,
                null=True,
                verbose_name="Ссылка на оплату",
            ),
        ),
    ]
