# Generated by Django 5.2.6 on 2025-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_paymentcourse_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Последний вход",
                null=True,
                verbose_name="Последний вход",
            ),
        ),
    ]
