# Generated by Django 5.2.6 on 2025-10-20 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_coursesubscription"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lesson",
            options={
                "ordering": ["id"],
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
