# Generated by Django 5.2.6 on 2025-10-23 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_alter_lesson_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_notification_sent",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Время последнего уведомления"
            ),
        ),
    ]
